server {
  listen 80;
  server_name localhost;

  # Всё в html/ кладётся в /usr/share/nginx/html, файлов может быть сколько угодно
  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /dashboard.html;
  }

  # Прокси для REST API на backend
  location /api/ {
    proxy_pass http://rest-server:8081/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
